- name: Update package repository cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Upgrade already installed packages
  ansible.builtin.apt:
    upgrade: safe
  become: true

- name: Remove stale depencendies
  ansible.builtin.apt:
    autoremove: yes
    purge: true
  become: true

- name: Install etckeeper
  ansible.builtin.apt:
    pkg:
      - etckeeper
  become: true

- name: Install essential packages
  ansible.builtin.apt:
    pkg:
      - tmux
      - vim
      - gedit
      - keepassxc
      - rsync
      - remmina
      - lsb-release
      - fceux
  become: true
