---

- name: Announce playbook intent
  hosts: 127.0.0.1

  tasks:
    - name: Announce playbook intent
      debug:
        msg: Provisioning host Debian Linux desktop

- name: Install essential packages
  hosts: 127.0.0.1

  tasks:
  - name: Update package repository cache
    ansible.builtin.apt:
      update_cache: yes
    become: true

  - name: Upgrade already installed packages
    ansible.builtin.apt:
      upgrade: safe
    become: true

  - name: Remove stale depencendies
    ansible.builtin.apt:
      autoremove: yes
      purge: true
    become: true

  - name: Install etckeeper
    ansible.builtin.apt:
      pkg:
        - etckeeper
    become: true

  - name: Install essential packages
    ansible.builtin.apt:
      pkg:
        - tmux
        - keepassxc
        - rsync
        - lsb-release
        # TODO provide remaining essential packages
    become: true

- name: Install Virtualbox
  hosts: 127.0.0.1

  tasks:
  - name: Register distribution codename
    ansible.builtin.shell: lsb_release -cs
    register: distribution_codename
    ignore_errors: false

  - name: Insert backports apt source
    ansible.builtin.lineinfile:
      path: /etc/apt/sources.list.d/backports.list
      line: "deb http://deb.debian.org/debian {{ distribution_codename.stdout }}-backports main contrib"
      create: yes
    become: true

  - name: Import fasttrack archive keyring
    ansible.builtin.apt:
      pkg:
        - fasttrack-archive-keyring
    become: true

  - name: Create fasttrack apt sources file
    ansible.builtin.file:
      path: /etc/apt/sources.list.d/fasttrack.list
      state: touch
      mode: '0644'
    become: true

  - name: Insert fasttrack apt sources
    ansible.builtin.blockinfile:
      path: /etc/apt/sources.list.d/fasttrack.list
      block: |
        deb http://fasttrack.debian.net/debian-fasttrack/ {{ distribution_codename.stdout }}-fasttrack main contrib
        deb http://fasttrack.debian.net/debian-fasttrack/ {{ distribution_codename.stdout }}-backports-staging main contrib
    become: true

  - name: Update package repository cache
    ansible.builtin.apt:
      update_cache: yes
    become: true

  - name: Install virtualbox package
    ansible.builtin.apt:
      pkg:
        - virtualbox
    become: true

- name: Create directory hierarchy
  hosts: 127.0.0.1

  tasks:
  - name: Create a directory for code repositories
    ansible.builtin.file:
      path: "{{ lookup('env','HOME') }}/my/repositories"
      state: directory
      mode: '0755'

# - name: Deploy configuration
#   hosts: 127.0.0.1
